# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    Makefile                                           :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: lwyl-the <marvin@42.fr>                    +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2018/11/20 15:27:59 by lwyl-the          #+#    #+#              #
#    Updated: 2018/11/20 15:28:00 by lwyl-the         ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

all:
	gcc -Wextra -Wall -Werror main.c putchar.c putstr.c display.c -o ft_display_file

clean:
	rm -f *.o

fclean: clean
	rm -f ft_display_file